model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.RVQModel
  params:
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [8,4]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: taming.data.calvin_lmdb.CalvinLMDBDataModule
  params:
    path_train: data_txt/train_D_gen.txt
    path_val: data_txt/test_D_gen.txt
    path_train_lmdb: /cvdata1/jihwan/calvin_lmdb/lmdb/train_D_gen
    path_val_lmdb: /cvdata1/jihwan/calvin_lmdb/lmdb/test_D_gen
    batch_size: 256
    num_workers: 16
    size: 32

